package org.ndexbio.model.object;

public enum TaskType
{
    PROCESS_UPLOADED_NETWORK,
    EXPORT_NETWORK_TO_FILE,
    SYSTEM_DELETE_NETWORK,
    SYSTEM_DATABASE_BACKUP,
    CREATE_NETWORK_CACHE,
    DELETE_NETWORK_CACHE
}
